# Generated by Django 4.0.1 on 2022-01-29 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
