# Generated by Django 4.0.1 on 2022-01-29 12:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name=uuid.uuid4),
        ),
    ]
